In [83]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
import matplotlib.pyplot as plt
import plotly.figure_factory as ff
import geopandas as gpd
import plotly.graph_objects as go


In [147]:
path = '/export/projects/Sen4Stat/WORK/CLASSIF/SITE_41/06-01_11-15/RF_OpenCV/SAMPLING_DESIGN_V25/CM/'

cm_csv = f'{path}SEN_2021_SITE_41_buf_0_LC_all_EXTENT_wall_to_wall_SEG_RATIO_100_LEVEL_grp_1_SD_25_FEAT_2_CLASSIF_RF_OpenCV_v1_CM_ori_FROM_grp_1_nb_TO_grp_A_nb.csv'

cm_html = f'{path}SEN_2021_SITE_41_buf_0_LC_all_EXTENT_wall_to_wall_SEG_RATIO_100_LEVEL_grp_1_SD_25_FEAT_2_CLASSIF_RF_OpenCV_v1_CM_ori_FROM_grp_1_nb_TO_grp_A_nb.html'

am_html = f'{path}SEN_2021_SITE_41_buf_0_LC_all_EXTENT_wall_to_wall_SEG_RATIO_100_LEVEL_grp_1_SD_25_FEAT_2_CLASSIF_RF_OpenCV_v1_CM_ori_FROM_grp_1_nb_TO_grp_A_nb_AM.html'

lut_xls = '/export/projects/Sen4Stat/WORK/LUT/crop_dictionary_new.xlsx'

point_rvalue_shp = '/export/projects/Sen4Stat/WORK/CLASSIF/SITE_41/06-01_11-15/RF_OpenCV/SAMPLING_DESIGN_V25/CM/SEN_2021_SITE_41_buf_0_LC_all_EXTENT_wall_to_wall_SEG_RATIO_100_LEVEL_grp_1_SD_25_FEAT_2_CLASSIF_RF_OpenCV_v1_grp_A.shp'

In [148]:
lut_df = pd.read_excel(lut_xls)

lut_df = lut_df[['grp_A_nb','grp_A']].drop_duplicates()

In [61]:
cm_df = pd.read_csv(cm_csv, index_col='labels')
cm = cm_df.to_numpy()

print(cm)
cm_df

[[   15     0     0     1     0     0   256     1]
 [ 3271 14840     0   261   146   179  6111    81]
 [    5     0   384    53     0    10    68     3]
 [    7     2    62  3042     0     6     6    10]
 [    1  2560     0     0 78892     0     0     0]
 [   32     2     0     7     0   261   731   183]
 [   36    30    19    46     0   422  5322   401]
 [   37     9     1    69     0   376   585  5833]]


5      6    7     8      9  112   118   142
labels                                                
5         15      0    0     1      0    0   256     1
6       3271  14840    0   261    146  179  6111    81
7          5      0  384    53      0   10    68     3
8          7      2   62  3042      0    6     6    10
9          1   2560    0     0  78892    0     0     0
112       32      2    0     7      0  261   731   183
118       36     30   19    46      0  422  5322   401
142       37      9    1    69      0  376   585  5833

In [56]:
point = gpd.read_file(point_rvalue_shp)

point.head()

index  id  sub_nb  area_db     area_ori  lc_nb               lc  grp_nb  \
0     12  12    1121   3630.9  1584.466393      1  Annual cropland      11   
1     12  12    1121   3630.9  1584.466393      1  Annual cropland      11   
2     12  12    1121   3630.9  1584.466393      1  Annual cropland      11   
3     12  12    1121   3630.9  1584.466393      1  Annual cropland      11   
4     12  12    1121   3630.9  1584.466393      1  Annual cropland      11   

       grp  class_nb  ...   pr_8 grp_A_nb  grp_A     area_buf  ID_SITE S2pix  \
0  Cereals       112  ...  Maize      112  Maize  1584.466393       12    14   
1  Cereals       112  ...  Maize      112  Maize  1584.466393       12    14   
2  Cereals       112  ...  Maize      112  Maize  1584.466393       12    14   
3  Cereals       112  ...  Maize      112  Maize  1584.466393       12    14   
4  Cereals       112  ...  Maize      112  Maize  1584.466393       12    14   

   originfid point_id  rvalue_1                        geometry  
0        189        0     118.0  POINT (397165.000 1506655.000)  
1        189        1     118.0  POINT (397175.000 1506655.000)  
2        189        2     118.0  POINT (397155.000 1506645.000)  
3        189        3     118.0  POINT (397165.000 1506645.000)  
4        189        4     118.0  POINT (397175.000 1506645.000)  

[5 rows x 35 columns]

In [62]:
y_true = point['grp_A_nb']
y_pred = point['rvalue_1']

In [77]:

classes = y_true.drop_duplicates().sort_values().to_list()

classes_name = lut_df[lut_df['grp_A_nb'].isin(classes)].sort_values('grp_A_nb')['grp_A'].to_list()



print(classes)
print(classes_name)

[5, 6, 7, 8, 9, 112, 118, 142]
['Shrub land', 'Forest', 'Bare soil', 'Build-up surface', 'Water bodies', 'Maize', 'Millets', 'Groundnuts']


In [116]:
cm = confusion_matrix(y_true, y_pred)

display(cm)


acc_metrics_str = classification_report(y_true, y_pred,target_names=classes_name, digits=2)
acc_metrics_dict = classification_report(y_true, y_pred,target_names=classes_name, digits=3, output_dict=True)


print(acc_metrics_str)



array([[   15,     0,     0,     1,     0,     0,   256,     1],
       [ 3271, 14840,     0,   261,   146,   179,  6111,    81],
       [    5,     0,   384,    53,     0,    10,    68,     3],
       [    7,     2,    62,  3042,     0,     6,     6,    10],
       [    1,  2560,     0,     0, 78892,     0,     0,     0],
       [   32,     2,     0,     7,     0,   262,   734,   183],
       [   36,    30,    19,    46,     0,   422,  5322,   401],
       [   37,     9,     1,    69,     0,   376,   585,  5833]])

                  precision    recall  f1-score   support

      Shrub land       0.00      0.05      0.01       273
          Forest       0.85      0.60      0.70     24889
       Bare soil       0.82      0.73      0.78       523
Build-up surface       0.87      0.97      0.92      3135
    Water bodies       1.00      0.97      0.98     81453
           Maize       0.21      0.21      0.21      1220
         Millets       0.41      0.85      0.55      6276
      Groundnuts       0.90      0.84      0.87      6910

        accuracy                           0.87    124679
       macro avg       0.63      0.65      0.63    124679
    weighted avg       0.92      0.87      0.89    124679



In [155]:
am_df = pd.DataFrame.from_dict(acc_metrics_dict).round(3)

oa = am_df['accuracy'][0]*100

am_df = am_df.iloc[: , :-3]

am_df = am_df.sort_values(by='support', ascending=False, axis=1)

class_name = am_df.columns.to_list()
precision = am_df.loc['precision'].to_list()
recall    = am_df.loc['recall'].to_list()
f1_score  = am_df.loc['f1-score'].to_list()

am_df

Water bodies     Forest  Groundnuts   Millets  Build-up surface  \
precision         0.998      0.851       0.896     0.407             0.874   
recall            0.969      0.596       0.844     0.848             0.970   
f1-score          0.983      0.701       0.869     0.550             0.920   
support       81453.000  24889.000    6910.000  6276.000          3135.000   

              Maize  Bare soil  Shrub land  
precision     0.209      0.824       0.004  
recall        0.215      0.734       0.055  
f1-score      0.212      0.777       0.008  
support    1220.000    523.000     273.000

In [159]:
site_nb = '41'

fig = go.Figure(data=[
    go.Bar(name='Precision', x=class_name, y=precision, text=precision, textposition='auto'),
    go.Bar(name='Recall', x=class_name, y=recall, text=recall, textposition='auto'),
    go.Bar(name='F1-score', x=class_name, y=f1_score, text=f1_score, textposition='auto')
])
# Change the bar mode
fig.update_layout(title_text=f'<i><b>SITE {site_nb} </b></i> <br><sup> Overall Accuracy : {oa}% </sup>',
                  barmode='group')

fig.show()

fig.write_html(am_html)

In [60]:
z = cm

# invert z idx values
z = z[::-1]

x = ['Shrub land', 'Forest', 'Bare soil', 'Build-up surface', 'Water bodies', 'Maize', 'Millets', 'Groundnuts']
y =  x[::-1].copy() # invert idx values of x

# change each element of z to type string for annotations
z_text = [[str(y) for y in x] for x in z]


print(z_text)

# set up figure 
fig = ff.create_annotated_heatmap(z,
                                  x=x,
                                  y=y,
                                  annotation_text=z_text,
                                  colorscale='spectral',
                                  reversescale=True)  # RdYlGn

# add title
fig.update_layout(title_text='<i><b>Confusion matrix</b></i>',
                  #xaxis = dict(title='x'),
                  #yaxis = dict(title='x')
                 )

# add custom xaxis title
fig.add_annotation(dict(font=dict(color="black",size=14),
                        x=0.5,
                        y=-0.15,
                        showarrow=False,
                        text="Predicted value",
                        xref="paper",
                        yref="paper"))

# add custom yaxis title
fig.add_annotation(dict(font=dict(color="black",size=14),
                        x=-0.35,
                        y=0.5,
                        showarrow=False,
                        text="Real value",
                        textangle=-90,
                        xref="paper",
                        yref="paper"))

# adjust margins to make room for yaxis title
fig.update_layout(margin=dict(t=50, l=200))

# add colorbar
fig['data'][0]['showscale'] = True
fig.show()

fig.write_html(cm_html)

[['37', '9', '1', '69', '0', '376', '585', '5833'], ['36', '30', '19', '46', '0', '422', '5322', '401'], ['32', '2', '0', '7', '0', '262', '734', '183'], ['1', '2560', '0', '0', '78892', '0', '0', '0'], ['7', '2', '62', '3042', '0', '6', '6', '10'], ['5', '0', '384', '53', '0', '10', '68', '3'], ['3271', '14840', '0', '261', '146', '179', '6111', '81'], ['15', '0', '0', '1', '0', '0', '256', '1']]
